name: profile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  ch_flutter_library:
    git:
      url: https://github.com/Chronoss0518/ch_flutter_library
      res: master

flutter:
  uses-material-design: true

  assets:
    - resource/image/